<a href="https://colab.research.google.com/github/Moksh4444/c-1/blob/main/csgoproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CSGo Project

Counter-Strike (CS) is a popular series of tactical first-person shooter (FPS) video games that have been enjoyed by gamers worldwide for many years. The series originated as a modification for the popular game Half-Life and quickly gained its own dedicated following. Here's an overview of Counter-Strike:

Gameplay Overview:

Counter-Strike is primarily a multiplayer game where two teams, the Counter-Terrorists (CTs) and the Terrorists (Ts), compete against each other.

The objective of each round varies based on the game mode, but the primary goals include:

Counter-Terrorists: Prevent the Terrorists from achieving their objectives, such as defusing a bomb or rescuing hostages.

Terrorists: Achieve their objectives, which may include planting a bomb at a designated site or holding hostages. Rounds are relatively short, typically lasting a few minutes, and players have only one life per round. When a player is eliminated, they must wait until the next round to respawn.

Key Features:

Weapons: Players can purchase and use a wide variety of firearms, grenades, and equipment. The choice of weaponry is an essential strategic element in the game.

Economy: Players earn in-game money based on their performance in the previous rounds. Money is used to buy weapons and equipment for the next round.

Maps: Counter-Strike features a range of maps, each with its own layout and objectives. Popular maps include Dust II, Mirage, Inferno, and more.

Teamwork: Successful gameplay in Counter-Strike heavily relies on teamwork, communication, and strategy. Players often coordinate their actions with their teammates to achieve objectives.

Competitive Play: Counter-Strike is well-known for its competitive scene, with professional esports tournaments held worldwide.

Popular Game Modes:

Bomb Defusal (de_): In this mode, Terrorists attempt to plant a bomb at one of the designated bomb sites, while Counter-Terrorists aim to prevent the bomb from being planted or defuse it if it's planted.

Hostage Rescue (cs_): In hostage rescue mode, Counter-Terrorists must rescue hostages held by the Terrorists, while the Terrorists aim to prevent the rescues.

Arms Race: A fast-paced mode where players cycle through a series of weapons, aiming to be the first to get a kill with each weapon.

Deathmatch: A mode where players respawn quickly and aim to get as many kills as possible within a set time limit.

Wingman: A 2v2 competitive mode with smaller maps and shorter rounds.

Counter-Strike has evolved over the years with different versions, including Counter-Strike 1.6, Counter-Strike: Source, and Counter-Strike: Global Offensive (CS:GO), which is the most recent and widely played installment as of my last knowledge update in September 2021.

CS:GO is known for its competitive gameplay, professional esports scene, and ongoing updates that have kept the game relevant and enjoyable for players worldwide. It remains a cornerstone of the first-person shooter genre.

Double-click (or enter) to edit

Problem Statemnt: based on the previous rounds record we have to build a best predictive model predicting which team is gonna a particular round

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('csgo_round_snapshots.csv')

In [3]:
df

time_left  ct_score  t_score          map  bomb_planted  ct_health  \
0         175.00       0.0      0.0     de_dust2         False      500.0   
1         156.03       0.0      0.0     de_dust2         False      500.0   
2          96.03       0.0      0.0     de_dust2         False      391.0   
3          76.03       0.0      0.0     de_dust2         False      391.0   
4         174.97       1.0      0.0     de_dust2         False      500.0   
...          ...       ...      ...          ...           ...        ...   
22903     174.91       5.0      6.0  de_overpass         False      500.0   
22904     114.95       5.0      6.0  de_overpass         False      500.0   
22905      94.95       5.0      6.0  de_overpass         False      500.0   
22906     174.91       6.0      6.0  de_overpass         False      500.0   
22907     114.95       6.0      6.0  de_overpass         False      500.0   

       t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0         500.0       0.0      0.0    4000.0  ...                  0.0   
1         500.0     400.0    300.0     600.0  ...                  0.0   
2         400.0     294.0    200.0     750.0  ...                  0.0   
3         400.0     294.0    200.0     750.0  ...                  0.0   
4         500.0     192.0      0.0   18350.0  ...                  0.0   
...         ...       ...      ...       ...  ...                  ...   
22903     500.0     299.0      0.0   18900.0  ...                  0.0   
22904     500.0     499.0    300.0    6600.0  ...                  2.0   
22905     497.0     499.0    497.0    6600.0  ...                  2.0   
22906     500.0     386.0      0.0   24350.0  ...                  0.0   
22907     500.0     486.0      0.0       NaN  ...                  NaN   

       ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                          0.0                     0.0   
1                          0.0                     2.0   
2                          0.0                     2.0   
3                          0.0                     0.0   
4                          0.0                     0.0   
...                        ...                     ...   
22903                      0.0                     0.0   
22904                      5.0                     1.0   
22905                      5.0                     1.0   
22906                      3.0                     0.0   
22907                      NaN                     NaN   

       ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                               0.0                          0.0   
1                               0.0                          0.0   
2                               0.0                          0.0   
3                               0.0                          0.0   
4                               0.0                          0.0   
...                             ...                          ...   
22903                           0.0                          0.0   
22904                           3.0                          0.0   
22905                           1.0                          0.0   
22906                           1.0                          0.0   
22907                           NaN                          NaN   

       ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                            0.0                       0.0   
1                            0.0                       0.0   
2                            0.0                       0.0   
3                            0.0                       0.0   
4                            0.0                       0.0   
...                          ...                       ...   
22903                        2.0                       0.0   
22904                        2.0                       1.0   
22905                        1.0                       0.0   
22906                        0.0                       0.0 

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22908 entries, 0 to 22907
Data columns (total 97 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   time_left                     22908 non-null  float64
 1   ct_score                      22908 non-null  float64
 2   t_score                       22908 non-null  float64
 3   map                           22908 non-null  object 
 4   bomb_planted                  22908 non-null  bool   
 5   ct_health                     22908 non-null  float64
 6   t_health                      22908 non-null  float64
 7   ct_armor                      22908 non-null  float64
 8   t_armor                       22908 non-null  float64
 9   ct_money                      22907 non-null  float64
 10  t_money                       22907 non-null  float64
 11  ct_helmets                    22907 non-null  float64
 12  t_helmets                     22907 non-null  float64
 13  c

In [8]:
df.columns

Index(['time_left', 'ct_score', 't_score', 'map', 'bomb_planted', 'ct_health',
       't_health', 'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets',
       't_helmets', 'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev',

In [9]:
df.isnull().sum().sum()

np.int64(88)

In [10]:
df.duplicated().sum()

np.int64(750)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22158 entries, 0 to 22907
Data columns (total 97 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   time_left                     22158 non-null  float64
 1   ct_score                      22158 non-null  float64
 2   t_score                       22158 non-null  float64
 3   map                           22158 non-null  object 
 4   bomb_planted                  22158 non-null  bool   
 5   ct_health                     22158 non-null  float64
 6   t_health                      22158 non-null  float64
 7   ct_armor                      22158 non-null  float64
 8   t_armor                       22158 non-null  float64
 9   ct_money                      22157 non-null  float64
 10  t_money                       22157 non-null  float64
 11  ct_helmets                    22157 non-null  float64
 12  t_helmets                     22157 non-null  float64
 13  ct_def

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['map'] = le.fit_transform(df['map'])
df['bomb_planted'] = le.fit_transform(df['bomb_planted'])
df['round_winner'] = le.fit_transform(df['round_winner'])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22158 entries, 0 to 22907
Data columns (total 97 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   time_left                     22158 non-null  float64
 1   ct_score                      22158 non-null  float64
 2   t_score                       22158 non-null  float64
 3   map                           22158 non-null  int64  
 4   bomb_planted                  22158 non-null  int64  
 5   ct_health                     22158 non-null  float64
 6   t_health                      22158 non-null  float64
 7   ct_armor                      22158 non-null  float64
 8   t_armor                       22158 non-null  float64
 9   ct_money                      22157 non-null  float64
 10  t_money                       22157 non-null  float64
 11  ct_helmets                    22157 non-null  float64
 12  t_helmets                     22157 non-null  float64
 13  ct_def

In [16]:
x = df.iloc[:,:-1]
y = df['round_winner']

In [17]:
x

time_left  ct_score  t_score  map  bomb_planted  ct_health  t_health  \
0         175.00       0.0      0.0    0             0      500.0     500.0   
1         156.03       0.0      0.0    0             0      500.0     500.0   
2          96.03       0.0      0.0    0             0      391.0     400.0   
3          76.03       0.0      0.0    0             0      391.0     400.0   
4         174.97       1.0      0.0    0             0      500.0     500.0   
...          ...       ...      ...  ...           ...        ...       ...   
22903     174.91       5.0      6.0    4             0      500.0     500.0   
22904     114.95       5.0      6.0    4             0      500.0     500.0   
22905      94.95       5.0      6.0    4             0      500.0     497.0   
22906     174.91       6.0      6.0    4             0      500.0     500.0   
22907     114.95       6.0      6.0    4             0      500.0     500.0   

       ct_armor  t_armor  ct_money  ...  ct_grenade_flashbang  \
0           0.0      0.0    4000.0  ...                   0.0   
1         400.0    300.0     600.0  ...                   0.0   
2         294.0    200.0     750.0  ...                   0.0   
3         294.0    200.0     750.0  ...                   0.0   
4         192.0      0.0   18350.0  ...                   0.0   
...         ...      ...       ...  ...                   ...   
22903     299.0      0.0   18900.0  ...                   1.0   
22904     499.0    300.0    6600.0  ...                   4.0   
22905     499.0    497.0    6600.0  ...                   4.0   
22906     386.0      0.0   24350.0  ...                   3.0   
22907     486.0      0.0       NaN  ...                   NaN   

       t_grenade_flashbang  ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                      0.0                      0.0                     0.0   
1                      0.0                      0.0                     2.0   
2                      0.0                      0.0                     2.0   
3                      0.0                      0.0                     0.0   
4                      0.0                      0.0                     0.0   
...                    ...                      ...                     ...   
22903                  0.0                      0.0                     0.0   
22904                  2.0                      5.0                     1.0   
22905                  2.0                      5.0                     1.0   
22906                  0.0                      3.0                     0.0   
22907                  NaN                      NaN                     NaN   

       ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                               0.0                          0.0   
1                               0.0                          0.0   
2                               0.0                          0.0   
3                               0.0                          0.0   
4                               0.0                          0.0   
...                             ...                          ...   
22903                           0.0                          0.0   
22904                           3.0                          0.0   
22905                           1.0                          0.0   
22906                           1.0                          0.0   
22907                           NaN                          NaN   

       ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                            0.0                       0.0   
1                            0.0                       0.0   
2                            0.0                       0.0   
3                            0.0                       0.0   
4                            0.0                       0.0   
...                          ...                       ...   
22903                        2.0                       0.0   
22904          

In [18]:
y

0        0
1        0
2        0
3        0
4        0
        ..
22903    0
22904    0
22905    0
22906    0
22907    2
Name: round_winner, Length: 22158, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=34)

In [21]:
x_train

time_left  ct_score  t_score  map  bomb_planted  ct_health  t_health  \
13565     175.00       7.0      8.0    0             0      500.0     500.0   
5363      114.95       5.0      9.0    0             0      500.0     500.0   
19897      30.22      11.0      9.0    2             1      200.0     355.0   
5948       69.49       4.0      5.0    3             0      494.0     499.0   
17123      34.91       8.0     13.0    3             0      400.0     403.0   
...          ...       ...      ...  ...           ...        ...       ...   
17245       3.62       7.0      8.0    6             1       59.0       0.0   
3226      174.94       3.0      3.0    1             0      500.0     500.0   
11067      94.94      17.0     15.0    4             0      500.0     392.0   
5416       94.94      15.0      7.0    0             0      420.0     500.0   
12048     174.87      14.0     11.0    4             0      500.0     500.0   

       ct_armor  t_armor  ct_money  ...  ct_grenade_flashbang  \
13565     300.0    100.0    1350.0  ...                   0.0   
5363      400.0    500.0     550.0  ...                   4.0   
19897     196.0    189.0    2550.0  ...                   2.0   
5948      484.0    499.0    4100.0  ...                   5.0   
17123     399.0    480.0    2700.0  ...                   3.0   
...         ...      ...       ...  ...                   ...   
17245     186.0      0.0    1500.0  ...                   0.0   
3226      285.0      0.0   17850.0  ...                   0.0   
11067     500.0    400.0   43450.0  ...                   5.0   
5416      498.0    476.0   18350.0  ...                   4.0   
12048     100.0      0.0   29750.0  ...                   1.0   

       t_grenade_flashbang  ct_grenade_smokegrenade  t_grenade_smokegrenade  \
13565                  1.0                      1.0                     0.0   
5363                   5.0                      0.0                     5.0   
19897                  0.0                      1.0                     0.0   
5948                   5.0                      2.0                     5.0   
17123                  1.0                      0.0                     1.0   
...                    ...                      ...                     ...   
17245                  0.0                      0.0                     0.0   
3226                   0.0                      1.0                     0.0   
11067                  3.0                      4.0                     3.0   
5416                   4.0                      3.0                     4.0   
12048                  0.0                      0.0                     0.0   

       ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
13565                           0.0                          0.0   
5363                            1.0                          0.0   
19897                           1.0                          0.0   
5948                            2.0                          0.0   
17123                           0.0                          0.0   
...                             ...                          ...   
17245                           0.0                          0.0   
3226                            0.0                          0.0   
11067                           2.0                          0.0   
5416                            2.0                          0.0   
12048                           0.0                          0.0   

       ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
13565                        0.0                       0.0   
5363                         0.0                       5.0   
19897                        0.0                       0.0   
5948                         0.0                       2.0   
17123                        0.0                       1.0   
...                          ...                       ...   
17245                        0.0                       0.0   
3226           

In [22]:
x_test

time_left  ct_score  t_score  map  bomb_planted  ct_health  t_health  \
1783       94.96      11.0      5.0    2             0      300.0     312.0   
18630      30.45       0.0      0.0    2             1      152.0     305.0   
21093      49.91       0.0      0.0    6             0      500.0     500.0   
3436      174.93       3.0      7.0    0             0      500.0     500.0   
6613      174.95       6.0      4.0    1             0      500.0     500.0   
...          ...       ...      ...  ...           ...        ...       ...   
9803      166.91       5.0      1.0    2             0      500.0     500.0   
6468       54.94      10.0      3.0    4             0      366.0     373.0   
14885      26.91       7.0      3.0    3             0      221.0      37.0   
11764      74.91      11.0      8.0    4             0      500.0     447.0   
6100      114.91       5.0      6.0    6             0      500.0     500.0   

       ct_armor  t_armor  ct_money  ...  ct_grenade_flashbang  \
1783      300.0    190.0     150.0  ...                   1.0   
18630     100.0    151.0     250.0  ...                   0.0   
21093     300.0    400.0     550.0  ...                   0.0   
3436      100.0      0.0   33800.0  ...                   0.0   
6613       94.0    178.0   19050.0  ...                   1.0   
...         ...      ...       ...  ...                   ...   
9803      273.0      0.0   32450.0  ...                   1.0   
6468      400.0    400.0    8300.0  ...                   3.0   
14885     278.0     85.0    5800.0  ...                   2.0   
11764     495.0    482.0    3800.0  ...                   4.0   
6100      500.0    300.0    4400.0  ...                   5.0   

       t_grenade_flashbang  ct_grenade_smokegrenade  t_grenade_smokegrenade  \
1783                   1.0                      2.0                     2.0   
18630                  0.0                      0.0                     0.0   
21093                  1.0                      0.0                     0.0   
3436                   0.0                      0.0                     0.0   
6613                   1.0                      0.0                     2.0   
...                    ...                      ...                     ...   
9803                   0.0                      0.0                     0.0   
6468                   3.0                      2.0                     3.0   
14885                  0.0                      0.0                     1.0   
11764                  4.0                      2.0                     1.0   
6100                   0.0                      4.0                     0.0   

       ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
1783                            1.0                          0.0   
18630                           0.0                          0.0   
21093                           0.0                          0.0   
3436                            0.0                          0.0   
6613                            0.0                          0.0   
...                             ...                          ...   
9803                            0.0                          0.0   
6468                            1.0                          0.0   
14885                           1.0                          0.0   
11764                           0.0                          0.0   
6100                            3.0                          0.0   

       ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
1783                         0.0                       1.0   
18630                        0.0                       0.0   
21093                        0.0                       0.0   
3436                         0.0                       0.0   
6613                         0.0                       0.0   
...                          ...                       ...   
9803                         0.0                       0.0   
6468           

In [23]:
y_train

13565    0
5363     1
19897    1
5948     1
17123    0
        ..
17245    0
3226     0
11067    0
5416     0
12048    0
Name: round_winner, Length: 17726, dtype: int64

In [24]:
y_test

1783     0
18630    1
21093    0
3436     0
6613     1
        ..
9803     0
6468     0
14885    0
11764    0
6100     0
Name: round_winner, Length: 4432, dtype: int64

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [26]:
x_train

array([[ 1.52781209,  0.06731393,  0.26067737, ..., -0.82322333,
        -0.15273043, -0.13780308],
       [ 0.39399175, -0.36058881,  0.4762485 , ...,  2.15563375,
        -0.15273043, -0.13780308],
       [-1.20581837,  0.92311941,  0.4762485 , ..., -0.82322333,
        -0.15273043, -0.13780308],
       ...,
       [ 0.01617751,  2.20682763,  1.76967525, ...,  0.3683195 ,
        -0.15273043, -0.13780308],
       [ 0.01617751,  1.77892489,  0.04510625, ...,  0.96409092,
        -0.15273043, -0.13780308],
       [ 1.52535753,  1.56497352,  0.90739075, ..., -0.82322333,
        -0.15273043, -0.13780308]])

In [27]:
x_test

array([[ 0.01655513,  0.92311941, -0.38603601, ..., -0.22745191,
        -0.15273043, -0.13780308],
       [-1.20147568, -1.43034565, -1.46389163, ..., -0.82322333,
        -0.15273043, -0.13780308],
       [-0.83404614, -1.43034565, -1.46389163, ..., -0.82322333,
        -0.15273043, -0.13780308],
       ...,
       [-1.26831538,  0.06731393, -0.81717826, ..., -0.22745191,
        -0.15273043, -0.13780308],
       [-0.36201436,  0.92311941,  0.26067737, ..., -0.22745191,
        -0.15273043, -0.13780308],
       [ 0.3932365 , -0.36058881, -0.17046488, ..., -0.82322333,
        -0.15273043, -0.13780308]])

In [28]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.impute import SimpleImputer

# Impute missing values with the mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x_train_imputed = imputer.fit_transform(x_train)
x_test_imputed = imputer.transform(x_test)

Lda = LinearDiscriminantAnalysis()
Lda.fit(x_train_imputed, y_train)

LinearDiscriminantAnalysis()

In [29]:
Lda.transform(x_test)

array([[ 0.27917427, -0.22481241],
       [ 1.14936623, -1.15315189],
       [ 0.35462418, -1.42647541],
       ...,
       [-1.76943094, -0.66988458],
       [-0.46279411, -0.05025095],
       [-1.05933011, -1.5029876 ]])

In [30]:
Lda.coef_

array([[-1.28534249e-01, -7.12161024e-03,  2.66527119e-02,
         3.15637108e-02, -1.42206154e-01,  3.07528410e-01,
        -2.06655493e-01,  3.15936650e-01, -4.84537896e-01,
         1.18186239e-01, -7.56060124e-02, -4.80993593e-02,
         4.36086875e-02,  4.65136825e-02,  3.20875720e-01,
         6.39066032e-02,  7.12351868e-02, -2.45718965e-01,
         8.68782330e-02, -3.69894308e-02,  1.39403458e-01,
        -1.37692442e-01,  3.03813406e-15, -1.94515297e-02,
        -1.14502288e-01, -8.53820704e-02,  3.94396625e-02,
        -3.08628527e-02,  6.95093681e-02, -1.78780230e-02,
        -2.89266397e-15, -1.18646421e-02,  3.23304755e-02,
        -4.99431885e-02, -3.10256474e-02, -2.44290892e-01,
         3.19219963e-16,  2.53558749e-16,  2.14474299e-02,
        -3.16608208e-02,  2.39745010e-01, -7.23983900e-02,
         4.35809869e-03, -4.19957602e-02,  1.74122912e-02,
        -9.55454109e-03, -1.62231887e-02, -1.18589353e-02,
         1.74817176e-02,  1.29802814e-02,  9.26909971e-0

In [31]:
Lda_coef=np.exp(np.abs(Lda.coef_))
Lda_coef

array([[1.13716037e+00, 1.00714703e+00, 1.02701107e+00, 1.03206713e+00,
        1.15281428e+00, 1.36005945e+00, 1.22955891e+00, 1.37154337e+00,
        1.62342464e+00, 1.12545370e+00, 1.07853756e+00, 1.04927491e+00,
        1.04457352e+00, 1.04761241e+00, 1.37833427e+00, 1.06599283e+00,
        1.07383375e+00, 1.27854021e+00, 1.09076385e+00, 1.03768205e+00,
        1.14958782e+00, 1.14762254e+00, 1.00000000e+00, 1.01964194e+00,
        1.12131521e+00, 1.08913311e+00, 1.04022773e+00, 1.03134405e+00,
        1.07198210e+00, 1.01803879e+00, 1.00000000e+00, 1.01193531e+00,
        1.03285878e+00, 1.05121137e+00, 1.03151196e+00, 1.27671566e+00,
        1.00000000e+00, 1.00000000e+00, 1.02167908e+00, 1.03216736e+00,
        1.27092504e+00, 1.07508356e+00, 1.00436761e+00, 1.04289006e+00,
        1.01756477e+00, 1.00960033e+00, 1.01635550e+00, 1.01192953e+00,
        1.01763542e+00, 1.01306489e+00, 1.09712267e+00, 1.00402496e+00,
        1.00000000e+00, 1.00000000e+00, 1.00968247e+00, 1.014526

In [32]:
lda_coef = Lda_coef.flatten()
lda_coef

array([1.13716037e+00, 1.00714703e+00, 1.02701107e+00, 1.03206713e+00,
       1.15281428e+00, 1.36005945e+00, 1.22955891e+00, 1.37154337e+00,
       1.62342464e+00, 1.12545370e+00, 1.07853756e+00, 1.04927491e+00,
       1.04457352e+00, 1.04761241e+00, 1.37833427e+00, 1.06599283e+00,
       1.07383375e+00, 1.27854021e+00, 1.09076385e+00, 1.03768205e+00,
       1.14958782e+00, 1.14762254e+00, 1.00000000e+00, 1.01964194e+00,
       1.12131521e+00, 1.08913311e+00, 1.04022773e+00, 1.03134405e+00,
       1.07198210e+00, 1.01803879e+00, 1.00000000e+00, 1.01193531e+00,
       1.03285878e+00, 1.05121137e+00, 1.03151196e+00, 1.27671566e+00,
       1.00000000e+00, 1.00000000e+00, 1.02167908e+00, 1.03216736e+00,
       1.27092504e+00, 1.07508356e+00, 1.00436761e+00, 1.04289006e+00,
       1.01756477e+00, 1.00960033e+00, 1.01635550e+00, 1.01192953e+00,
       1.01763542e+00, 1.01306489e+00, 1.09712267e+00, 1.00402496e+00,
       1.00000000e+00, 1.00000000e+00, 1.00968247e+00, 1.01452627e+00,
      

In [33]:
feature_name = x.columns
feature_name

Index(['time_left', 'ct_score', 't_score', 'map', 'bomb_planted', 'ct_health',
       't_health', 'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets',
       't_helmets', 'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev',

In [34]:
df_features_imp = pd.DataFrame({'features':feature_name,'imp_value' : np.mean(Lda_coef, axis=0)})

In [35]:
df_features_imp

features  imp_value
0                     time_left   2.631386
1                      ct_score   1.011631
2                       t_score   1.046942
3                           map   1.661850
4                  bomb_planted   1.397611
..                          ...        ...
91  t_grenade_incendiarygrenade   1.044272
92    ct_grenade_molotovgrenade   1.087170
93     t_grenade_molotovgrenade   1.363682
94      ct_grenade_decoygrenade   1.125110
95       t_grenade_decoygrenade   1.016429

[96 rows x 2 columns]

In [36]:
top20_fea = df_features_imp.nlargest(20,'imp_value')

In [37]:
top20_fea

features     imp_value
8            t_armor  1.556952e+08
12         t_helmets  1.493459e+06
14  ct_players_alive  9.920660e+05
6           t_health  2.251551e+05
5          ct_health  1.711441e+05
7           ct_armor  2.422326e+04
15   t_players_alive  1.640132e+02
40    ct_weapon_m4a4  8.512763e+01
35    t_weapon_glock  3.278516e+01
10           t_money  1.127071e+01
20     ct_weapon_awp  6.111226e+00
64   ct_weapon_sg553  4.774771e+00
17     t_weapon_ak47  3.712134e+00
50     ct_weapon_mp9  3.671685e+00
65    t_weapon_sg553  3.071282e+00
28   ct_weapon_famas  2.947488e+00
16    ct_weapon_ak47  2.937841e+00
11        ct_helmets  2.932319e+00
0          time_left  2.631386e+00
13    ct_defuse_kits  2.491924e+00

In [38]:
index_fea = top20_fea.index
index_fea

Index([8, 12, 14, 6, 5, 7, 15, 40, 35, 10, 20, 64, 17, 50, 65, 28, 16, 11, 0,
       13],
      dtype='int64')

In [80]:
x_train = x_train[:,index_fea]
x_train

IndexError: index 8 is out of bounds for axis 1 with size 3

In [77]:
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()
model_tree.fit(x_train_selected, y_train)

y_pred_tree = model_tree.predict(x_test_selected)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Decision Tree Confusion Matrix:\n", confusion_matrix(y_test, y_pred_tree))

Decision Tree Accuracy: 0.805731046931408
Decision Tree Confusion Matrix:
 [[1719  424]
 [ 437 1852]]


In [40]:
x_test = x_test[:,index_fea]
x_test

array([[-0.65152514, -0.9527508 , -1.00193602, ...,  0.4931134 ,
         0.01655513, -0.3869069 ],
       [-0.87609015, -1.45965483, -1.81650882, ..., -1.15799832,
        -1.20147568, -0.3869069 ],
       [ 0.55767102, -1.45965483,  0.62720956, ..., -1.15799832,
        -0.83404614,  0.23705132],
       ...,
       [-1.25612323, -0.9527508 , -1.00193602, ..., -0.05725717,
        -1.26831538,  0.23705132],
       [ 1.02983333,  1.07486533,  0.62720956, ...,  1.59385455,
        -0.36201436,  1.48496774],
       [-0.01813668, -1.45965483,  0.62720956, ...,  0.4931134 ,
         0.3932365 ,  1.48496774]])

In [46]:
from sklearn.linear_model import LogisticRegression
model_logistick = LogisticRegression()

# Select features from the imputed data
x_train_selected = x_train_imputed[:, index_fea]
x_test_selected = x_test_imputed[:, index_fea]

model_logistick.fit(x_train_selected, y_train)

LogisticRegression()

In [47]:
y_pred = model_logistick.predict(x_test)

In [51]:
from sklearn.metrics import *
accuracy_score(y_test,y_pred)

0.7533844765342961

In [53]:
confusion_matrix(y_test,y_pred)

array([[1586,  557],
       [ 536, 1753]])

In [59]:
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()
model_tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [79]:
y_pred=model_tree.predict(x_test)

In [81]:
accuracy_score(y_test,y_pred)

0.805731046931408

In [83]:
confusion_matrix(y_test,y_pred)

array([[1719,  424],
       [ 437, 1852]])

In [86]:
from sklearn.ensemble import RandomForestClassifier
model_forest = RandomForestClassifier()
model_forest.fit(x_train_selected,y_train)

RandomForestClassifier()

In [87]:
y_pred = model_forest.predict(x_test_selected)

In [88]:
accuracy_score(y_test,y_pred)

0.8603339350180506

In [89]:
confusion_matrix(y_test,y_pred)

array([[1849,  294],
       [ 325, 1964]])